name: Tron_Tx_CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
      
      - name: 'Create env file'
        run: |
          touch .env
          # Database (same as sendcoins)
          DB_USER='postgres'
          DB_HOST='database-1.cihiwyaqc8kv.us-east-1.rds.amazonaws.com'
          DB_NAME='sendcoin_pgdb'
          DB_PASSWORD='Sendcoins________INC1.'
          DB_PORT=5432

          # Tron Network
          TRON_NETWORK=shasta
          # TRON_NETWORK=mainnet
          TRON_PRO_API_KEY=b5d8d898-3e48-414d-9336-1c861e8926a5
          MASTER_WALLET_TRON_PRIVATE_KEY=CA860ADB139630DCFA8EE5558D5DC13B9E47384DF7B6CEF4BD4F30889EFDE214
          MASTER_WALLET_TRON_ADDRESS=TQanRDRe3FMm4Qx5VR9iCwgW5tiyVeHsFM
          MIN_TRX_FOR_GAS=20
          FEE_LIMIT=20000000

          # BSC Network
          BSC_RPC_URL=https://bsc-dataseed1.binance.org
          MASTER_WALLET_BSC_PRIVATE_KEY=
          MASTER_WALLET_BSC_ADDRESS=
          MIN_BNB_FOR_GAS=0.005

          # Ethereum Network
          ETH_RPC_URL=https://mainnet.infura.io/v3/96272c583c704637946557e18fb3508e
          MASTER_WALLET_ETH_PRIVATE_KEY=
          MASTER_WALLET_ETH_ADDRESS=
          MIN_ETH_FOR_GAS=0.01

          # Optional: CLI-only
          SENDER_WALLET_PRIVATE_KEY=21F74827971220F42DEBA40D301EE612A194F39DA3D7680031BC6A30561DF00C
          SENDER_WALLET_ADDRESS=THZkY44qncyKCrkfJ8DnYvzMEPHyewujou

          # TRC20 contract overrides (Shasta testnet)
          USDT_CONTRACT=TG3XXyExBkPp9nzdajDZsozEu4BkaSJozs
          USDC_CONTRACT=TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8

          # API Security
          API_SECRET=0894cd7b39803b00d83c6116aba483809b13f2d2785e135325eddda9ee1c8274
          
          CRON_SECRET=5b2a0c235b9cdc33cb564611a20ffd1c6543bd75bf9507b8d1b41bdac4d5e15c

          RESEND_API_KEY=re_bKUr53bk_6YC1co3wM27xYCnfxbgAd7Rs
          # cat .env

      - name: Start or reload app with PM2
        run: |
          npm install -g pm2
          pm2 describe Tron-tx > /dev/null && pm2 restart Tron-tx || pm2 start npm --name "Tron-tx" -- start
          pm2 save


      # - name: Start/Restart app using ecosystem file
      #   run: |
      #     if pm2 describe "landingpage" > /dev/null 2>&1; then
      #       echo "App exists, reloading..."
      #       pm2 reload ecosystem.config.js
      #     else
      #       echo "Starting app..."
      #       pm2 start ecosystem.config.js
      #     fi
      
      # - name: Save PM2 configuration
      #   run: pm2 save    

      
      # - name: Run App
      #   run: npm start    
