name: Tron_Tx_CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
      
      - name: 'Create env file'
        run: |
          touch .env
            # Database (same as sendcoins)
            DB_USER='postgres'
            # cat .env

      - name: Start or reload app with PM2
        run: |
          npm install -g pm2
          pm2 describe Tron-tx > /dev/null && pm2 restart Tron-tx || pm2 start npm --name "Tron-tx" -- start
          pm2 save


      # - name: Start/Restart app using ecosystem file
      #   run: |
      #     if pm2 describe "landingpage" > /dev/null 2>&1; then
      #       echo "App exists, reloading..."
      #       pm2 reload ecosystem.config.js
      #     else
      #       echo "Starting app..."
      #       pm2 start ecosystem.config.js
      #     fi
      
      # - name: Save PM2 configuration
      #   run: pm2 save    

      
      # - name: Run App
      #   run: npm start    
